//
// Created by 구현우 on 2024/04/28.
//

#ifndef MY_OPENCL_SETTING_H
#define MY_OPENCL_SETTING_H

#define LINEAR_KERNEL_VERSION 4

#define CROSS_ATTENTION_KERNEL_VERSION 2

#endif //MY_OPENCL_SETTING_H
